version: 2

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/clojure:lein-2.7.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - clj-pgp-{{ checksum "project.clj" }}
            - clj-pgp-
      - run: lein deps
      - run: lein check
      - run: lein test
      - run: lein coverage --codecov
      - save_cache:
          key: clj-pgp-{{ checksum "project.clj" }}
          paths:
            - ~/.m2
      - store_artifacts:
          path: target/coverage
          destination: coverage
      - run:
          name: Publish Coverage
          command: "(curl -s https://codecov.io/bash > codecov) && bash codecov -f target/coverage/codecov.json"
